01_hh_l: 10
05_hh_l: 0
08_hh_l: 64
10_hh_l: 1024
1_6_hh_l: 128
30_hh_l: 1100
3_hh_l: 256
5_hh_l: 512
60_hh_l: 1200
hvip_cfg_pwm_ch: 15.0
hvip_cfg_pwm_pips: 15.0
hvip_cfg_pwm_sipm: 15.0
hvip_cfg_vlt_ch: 26.0
hvip_cfg_vlt_pips: 40.0
hvip_cfg_vlt_sipm: 26.0
interval_measure: 10
mpp_id: 14
