01_hh_l: 40
05_hh_l: 160
08_hh_l: 340
10_hh_l: 1000
1_6_hh_l: 680
30_hh_l: 1110
3_hh_l: 800
5_hh_l: 900
60_hh_l: 1210
hvip_cfg_pwm_ch: 20.34
hvip_cfg_pwm_pips: 17.4
hvip_cfg_pwm_sipm: 17.84
hvip_cfg_vlt_ch: 28.04
hvip_cfg_vlt_pips: 40.04
hvip_cfg_vlt_sipm: 34.04
interval_measure: 720
mpp_id: 14
