01_hh_l: 10
05_hh_l: 0
08_hh_l: 64
10_hh_l: 1024
1_6_hh_l: 128
30_hh_l: 1100
3_hh_l: 256
5_hh_l: 512
60_hh_l: 1200
hvip_cfg_pwm_ch: 20.43
hvip_cfg_pwm_pips: 17.4
hvip_cfg_pwm_sipm: 17.81
hvip_cfg_vlt_ch: 24.0
hvip_cfg_vlt_pips: 24.0
hvip_cfg_vlt_sipm: 24.0
interval_measure: 720
mpp_id: 14
