01_hh_l: 30
05_hh_l: 200
08_hh_l: 600
10_hh_l: 1450
1_6_hh_l: 1200
30_hh_l: 1000
3_hh_l: 1920
5_hh_l: 2800
60_hh_l: 2000
hvip_cfg_pwm_ch: 16.0
hvip_cfg_pwm_pips: 24.0
hvip_cfg_pwm_sipm: 20.0
hvip_cfg_vlt_ch: 30.0
hvip_cfg_vlt_pips: 40.0
hvip_cfg_vlt_sipm: 34.5
interval_measure: 720
lineEdit_pwm_max_ch: 18.0
lineEdit_pwm_max_pips: 26.0
lineEdit_pwm_max_sipm: 21.7
mpp_id: 14
