01_hh_l: 19
05_hh_l: 15
08_hh_l: 15
10_hh_l: 15
1_6_hh_l: 15
30_hh_l: 15
3_hh_l: 15
5_hh_l: 15
60_hh_l: 15
hvip_cfg_pwm_ch: 20.3
hvip_cfg_pwm_pips: 22.5
hvip_cfg_pwm_sipm: 21.65
hvip_cfg_vlt_ch: 30.0
hvip_cfg_vlt_pips: 39.0
hvip_cfg_vlt_sipm: 34.5
interval_measure: 10
lineEdit_pwm_max_ch: 20.7
lineEdit_pwm_max_pips: 22.7
lineEdit_pwm_max_sipm: 18.0
mpp_id: 14
